// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" }
import * as $0 from "./routes/index.jsx"
import * as $1 from "./routes/javascript.jsx"
import * as $2 from "./routes/showcase.jsx"
import * as $$0 from "./islands/Counter.tsx"

const manifest = {
  routes: {
    "./routes/index.jsx": $0,
    "./routes/javascript.jsx": $1,
    "./routes/showcase.jsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
